CREATE DATABASE TRUNGTAMANHVAN_TEST
GO

USE TRUNGTAMANHVAN_TEST
GO

CREATE TABLE ACCOUNT
(
	USERNAME CHAR(100) NOT NULL UNIQUE,
	PASS_WORD CHAR(100) NOT NULL,
)
INSERT INTO ACCOUNT VALUES ('admin1', '1234')
INSERT INTO ACCOUNT VALUES ('admin2', '1234')
INSERT INTO ACCOUNT VALUES ('admin3', '1234')

SELECT *FROM ACCOUNT 
where USERNAME='admin1' and PASS_WORD='1234'

CREATE TABLE ACCOUNT_TEACHER
(
	USERNAME CHAR(100) NOT NULL UNIQUE,
	PASS_WORD CHAR(100) NOT NULL,
)
INSERT INTO ACCOUNT_TEACHER VALUES ('teacher1', '1234')
INSERT INTO ACCOUNT_TEACHER VALUES ('teacher2', '1234')

CREATE TABLE ACCOUNT_STUDENT
(
	USERNAME CHAR(100) NOT NULL UNIQUE,
	PASS_WORD CHAR(100) NOT NULL,
)
INSERT INTO ACCOUNT_STUDENT VALUES ('student1', '1234')
INSERT INTO ACCOUNT_STUDENT VALUES ('student2', '1234')


CREATE TABLE GIAOVIEN (
	GVID INT IDENTITY (1, 1) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	CMND CHAR(20) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT CHAR(20)NOT NULL,
	DIACHI NVARCHAR(4000) NOT NULL,
	TRINHDO NVARCHAR(4000) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	UUDIEM NVARCHAR(4000),
	)
	
INSERT INTO GIAOVIEN( HOTEN,CMND,GIOITINH,NGAYSINH,SDT,DIACHI,TRINHDO,EMAIL,UUDIEM) VALUES 
	(N'Nguyễn Văn A','2845623645','Nam','4/4/1988','0155555555',N'Tp Hồ chí Minh','Cử nhân','AC@gmail.com','Chuyên môn cao')

	GO
	CREATE TABLE HOCSINH(
	HSID INT IDENTITY (1, 1) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(4000) NOT NULL,
	SDT CHAR(20) NOT NULL,
	CMND CHAR(20) NULL,
	EMAIL char(100) not null,)
	select * from HOCSINH

	INSERT INTO HOCSINH(HOTEN, GIOITINH, NGAYSINH, DIACHI, SDT, CMND, EMAIL) VALUES 
	(N'Nguyễn Văn B','Nam','4/4/2000',N'Tp Hồ chí Minh','0155555555','272111444','B@gmail.com')













CREATE TABLE ACCOUNT
(
	ACCID INT IDENTITY (1, 1) PRIMARY KEY,
	PHANQUYEN NVARCHAR(30),
	USERNAME CHAR(100) NOT NULL UNIQUE,
	PASS_WORD CHAR(100) NOT NULL,
	EMAIL CHAR(100) NOT NULL,
	NGANSACH INT NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	CMND CHAR(20) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT CHAR(20) NOT NULL,
	DIACHI NVARCHAR(4000) NOT NULL,
	TRINHDO NVARCHAR(4000) NULL,
	UUDIEM NVARCHAR(4000) NULL,
	AVARTAR IMAGE NULL
)
	
GO
CREATE TABLE GIAOVIEN (
	GVID INT IDENTITY (1, 1) PRIMARY KEY,
	ACCID INT FOREIGN KEY(ACCID) REFERENCES ACCOUNT(ACCID) NOT NULL UNIQUE,
	HOTEN NVARCHAR(100) NOT NULL,
	CMND CHAR(20) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	SDT CHAR(20)NOT NULL,
	QUEQUAN NVARCHAR(500) NOT NULL,
	DIACHI NVARCHAR(4000) NOT NULL,
	TRUONGDAOTAO NVARCHAR(500) NOT NULL,
	TRINHDO NVARCHAR(4000) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	UUDIEM NVARCHAR(4000),
	AVARTAR IMAGE,)

	--INSERT INTO GIAOVIEN(GVID , ACCID, HOTEN,CMND,GIOITINH,NGAYSINH,SDT,QUEQUAN,DIACHI,TRUONGDAOTAO,TRINHDO,UUDIEM,AVARTAR) VALUES ('1', '20', N'Nguyễn Văn A','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','Chuyên môn cao','ninh.jpg')
	GO
	CREATE TABLE HOCSINH(
	HSID INT IDENTITY (1, 1) PRIMARY KEY,
	ACCID INT FOREIGN KEY(ACCID) REFERENCES ACCOUNT(ACCID) NOT NULL UNIQUE,
	HOTEN NVARCHAR(100) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	DIACHI NVARCHAR(4000) NOT NULL,
	SDT CHAR(20) NOT NULL,
	CMND CHAR(20) NOT NULL,
	EMAIL char(100) not null,)

	
	SET IDENTITY_INSERT ACCOUNT ON
	INSERT INTO ACCOUNT(ACCID,PHANQUYEN,USERNAME,PASSWORD,EMAIL,NGANSACH) VALUES
	('1','ADMIN','ADMIN1','ADMIN1','admin1@gmail.com','0'),
	('2','ADMIN','ADMIN2','ADMIN2','admin2@gmail.com','0'),
	('3','GIAOVIEN','GIAOVIEN1','GIAOVIEN1','giaovien1@gmail.com','100'),
	('4','GIAOVIEN','GIAOVIEN2','GIAOVIEN2','giaovien2@gmail.com','200'),
	('5','HOCSINH','HOCSINH1','HOCSINH1','hocsinh1@gmail.com','350'),
	('6','HOCSINH','HOCSINH2','HOCSINH2','hocsinh2@gmail.com','350')
	SET IDENTITY_INSERT ACCOUNT OFF

	SET IDENTITY_INSERT GIAOVIEN ON
	INSERT INTO GIAOVIEN(GVID, ACCID, HOTEN,CMND,GIOITINH,NGAYSINH,SDT,QUEQUAN,DIACHI,TRUONGDAOTAO,TRINHDO,EMAIL,UUDIEM,AVARTAR) VALUES 
	('1', '3', N'Nguyễn Văn A','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('2', '2', N'Nguyễn Văn B','5555556664','Nam','9/4/1988','0155545555',N'Đồng Nai',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','aw@gmail.com','Chuyên môn cao','ninh.jpg'),
	('3', '1', N'Nguyễn Thị C','2845313645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('4', '4', N'Nguyễn Văn D','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('5', '6', N'Nguyễn Văn E','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('6', '5', N'Nguyễn Văn F','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	INSERT INTO GIAOVIEN(GVID, ACCID, HOTEN,CMND,GIOITINH,NGAYSINH,SDT,QUEQUAN,DIACHI,TRUONGDAOTAO,TRINHDO,EMAIL,UUDIEM,AVARTAR) VALUES 
	('7', '9', N'Nguyễn Văn A','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg')

	SET IDENTITY_INSERT HOCSINH ON
	INSERT INTO HOCSINH(HSID, ACCID, HOTEN, GIOITINH, NGAYSINH, NGHENGHIEP, DIACHI, SDT, CMND, EMAIL) VALUES 
	('1', '3', N'Nguyễn Văn A','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('2', '2', N'Nguyễn Văn B','5555556664','Nam','9/4/1988','0155545555',N'Đồng Nai',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','aw@gmail.com','Chuyên môn cao','ninh.jpg'),
	('3', '1', N'Nguyễn Thị C','2845313645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('4', '4', N'Nguyễn Văn D','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('5', '6', N'Nguyễn Văn E','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg'),
	('6', '5', N'Nguyễn Văn F','2845623645','Nam','4/4/1988','0155555555',N'Đồng Tháp',N'Tp Hồ chí Minh',N'Đại học Sư phạm kỹ thuật TP HCM','Cử nhân','AC@gmail.com','Chuyên môn cao','ninh.jpg')
	GO
	GO


	CREATE TABLE LICHSUGIAODICH(
	GDID INT IDENTITY (1, 1) PRIMARY KEY,
	ACCID INT FOREIGN KEY(ACCID) REFERENCES ACCOUNT(ACCID) NOT NULL,
	LMID INT FOREIGN KEY(LMID) REFERENCES DANHSACHMOLOP(LMID) NOT NULL,
	SOTIEN INT NOT NULL,
	THOIGIANGIAODICH DATETIME,)
	GO

	CREATE TABLE DANHSACHMOLOP(
	LMID INT IDENTITY (1, 1) PRIMARY KEY,--LỚP MỚI ID 
	LHID INT REFERENCES LOPHOC(ID) NOT NULL,
	ACCID INT REFERENCES ACCOUNT(ACCID) NOT NULL,
	DIACHI NVARCHAR(500) NOT NULL,
	MUCLUONG INT NOT NULL,
	SDTLIENHE CHAR(20) NOT NULL,
	THOIGIANDANGKY DATETIME NOT NULL,
	SOBUOI INT NOT NULL,
	HINHTHUCDAY NVARCHAR(50) NOT NULL,
	THOIGIANHOC NVARCHAR(50) NOT NULL,
	THONGTINHOCVIEN NVARCHAR(500),
	YEUCAUGIAOVIEN NVARCHAR(500),
	TRANGTHAI NVARCHAR(50) NOT NULL,)

	GO
	CREATE TABLE LOPHOC
(
	ID INT IDENTITY (1, 1) PRIMARY KEY,
	TENLOP NVARCHAR(50) NOT NULL UNIQUE
)
	
	
	SELECT *FROM GIAOVIEN

	DROP DATABASE TRUNGTAMANHVAN;
GO
USE QLSV